# Generated by Django 2.1.3 on 2018-11-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='passport_data',
            field=models.CharField(max_length=128),
        ),
    ]
